//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleCloudExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogleCloudExtension.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to help Google by reporting usage statics?.
        /// </summary>
        public static string AnalyticsPromptMessage {
            get {
                return ResourceManager.GetString("AnalyticsPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Statistics.
        /// </summary>
        public static string AnalyticsPromptTitle {
            get {
                return ResourceManager.GetString("AnalyticsPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Authorized Network.
        /// </summary>
        public static string AuthorizedNetworksWindowAddNetworkButton {
            get {
                return ResourceManager.GetString("AuthorizedNetworksWindowAddNetworkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Authorized Networks.
        /// </summary>
        public static string AuthorizedNetworksWindowCaption {
            get {
                return ResourceManager.GetString("AuthorizedNetworksWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter IPv4 in CIDR notation (e.g. 192.168.2.0/24)..
        /// </summary>
        public static string AuthorizedNetworksWindowInvalidCidrFormatErrorMessage {
            get {
                return ResourceManager.GetString("AuthorizedNetworksWindowInvalidCidrFormatErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Subnet..
        /// </summary>
        public static string AuthorizedNetworksWindowInvalidCidrFormatErrorTitle {
            get {
                return ResourceManager.GetString("AuthorizedNetworksWindowInvalidCidrFormatErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage authorized networks that can connect to your instance..
        /// </summary>
        public static string AuthorizedNetworksWindowMessage {
            get {
                return ResourceManager.GetString("AuthorizedNetworksWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name (Optional):.
        /// </summary>
        public static string AuthorizedNetworksWindowNameTextBoxTitle {
            get {
                return ResourceManager.GetString("AuthorizedNetworksWindowNameTextBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network (CIDR Notation):.
        /// </summary>
        public static string AuthorizedNetworksWindowValueTextBoxTitle {
            get {
                return ResourceManager.GetString("AuthorizedNetworksWindowValueTextBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable API.
        /// </summary>
        public static string CloudExploreDisabledApiEnableApiMenuHeader {
            get {
                return ResourceManager.GetString("CloudExploreDisabledApiEnableApiMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects found, to create a project navigate to the Google Cloud Console..
        /// </summary>
        public static string CloudExploreNoProjectMessage {
            get {
                return ResourceManager.GetString("CloudExploreNoProjectMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was canceled..
        /// </summary>
        public static string CloudExploreOperationCanceledMessage {
            get {
                return ResourceManager.GetString("CloudExploreOperationCanceledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation took too long to complete and timed out..
        /// </summary>
        public static string CloudExploreOperationTimeoutMessage {
            get {
                return ResourceManager.GetString("CloudExploreOperationTimeoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the Google Cloud Console for other services.
        /// </summary>
        public static string CloudExplorerConsoleLinkCaption {
            get {
                return ResourceManager.GetString("CloudExplorerConsoleLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the list of Google Cloud App Engine instances.
        /// </summary>
        public static string CloudExplorerGaeFailedInstancesMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGaeFailedInstancesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the list of Google Cloud App Engine services.
        /// </summary>
        public static string CloudExplorerGaeFailedServicesMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGaeFailedServicesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load instances..
        /// </summary>
        public static string CloudExplorerGaeFailedToLoadInstancesCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGaeFailedToLoadInstancesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load services..
        /// </summary>
        public static string CloudExplorerGaeFailedToLoadServicesCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGaeFailedToLoadServicesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load versions..
        /// </summary>
        public static string CloudExplorerGaeFailedToLoadVersionsCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGaeFailedToLoadVersionsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the list of Google Cloud App Engine versions.
        /// </summary>
        public static string CloudExplorerGaeFailedVersionsMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGaeFailedVersionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Engine Release.
        /// </summary>
        public static string CloudExplorerGaeInstanceAppEngineReleaseDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeInstanceAppEngineReleaseDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Latency.
        /// </summary>
        public static string CloudExplorerGaeInstanceAverageLatencyDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeInstanceAverageLatencyDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Properties.
        /// </summary>
        public static string CloudExplorerGaeInstanceCategory {
            get {
                return ResourceManager.GetString("CloudExplorerGaeInstanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory Usage.
        /// </summary>
        public static string CloudExplorerGaeInstanceMemoryUsageDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeInstanceMemoryUsageDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string CloudExplorerGaeInstanceStartTimeDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeInstanceStartTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Virtual Machine Properties.
        /// </summary>
        public static string CloudExplorerGaeInstanceVirtualMachineCategory {
            get {
                return ResourceManager.GetString("CloudExplorerGaeInstanceVirtualMachineCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string CloudExplorerGaeInstanceVirtualMachineIdDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeInstanceVirtualMachineIdDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string CloudExplorerGaeInstanceVirtualMachineNameDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeInstanceVirtualMachineNameDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CloudExplorerGaeInstanceVirtualMachineStatusDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeInstanceVirtualMachineStatusDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone.
        /// </summary>
        public static string CloudExplorerGaeInstanceVirtualMachineZoneDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeInstanceVirtualMachineZoneDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading instances....
        /// </summary>
        public static string CloudExplorerGaeLoadingInstancesCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGaeLoadingInstancesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading services....
        /// </summary>
        public static string CloudExplorerGaeLoadingServicesCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGaeLoadingServicesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading versions....
        /// </summary>
        public static string CloudExplorerGaeLoadingVersionCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGaeLoadingVersionCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No instances found..
        /// </summary>
        public static string CloudExplorerGaeNoInstancesFoundCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGaeNoInstancesFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services found..
        /// </summary>
        public static string CloudExplorerGaeNoServicesFoundCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGaeNoServicesFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No versions found..
        /// </summary>
        public static string CloudExplorerGaeNoVersionsFoundCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGaeNoVersionsFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google App Engine.
        /// </summary>
        public static string CloudExplorerGaeRootNodeCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGaeRootNodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Properties.
        /// </summary>
        public static string CloudExplorerGaeServiceCategory {
            get {
                return ResourceManager.GetString("CloudExplorerGaeServiceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Properties.
        /// </summary>
        public static string CloudExplorerGaeVersionCategory {
            get {
                return ResourceManager.GetString("CloudExplorerGaeVersionCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Time.
        /// </summary>
        public static string CloudExplorerGaeVersionCreationTimeDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeVersionCreationTimeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Class.
        /// </summary>
        public static string CloudExplorerGaeVersionInstanceClassDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeVersionInstanceClassDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk (GB).
        /// </summary>
        public static string CloudExplorerGaeVersionResoucesDiskDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeVersionResoucesDiskDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory (GB).
        /// </summary>
        public static string CloudExplorerGaeVersionResoucesMemoryDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeVersionResoucesMemoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Resouces Properties.
        /// </summary>
        public static string CloudExplorerGaeVersionResourcesCategory {
            get {
                return ResourceManager.GetString("CloudExplorerGaeVersionResourcesCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Machine.
        /// </summary>
        public static string CloudExplorerGaeVersionVirtualMachineDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGaeVersionVirtualMachineDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials Error.
        /// </summary>
        public static string CloudExplorerGceFailedToGetOauthCredentialsCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceFailedToGetOauthCredentialsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to fetch OAUTH credentials for account {0}, please login again..
        /// </summary>
        public static string CloudExplorerGceFailedToGetOauthCredentialsMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGceFailedToGetOauthCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start instance {0}. {1}.
        /// </summary>
        public static string CloudExplorerGceFailedToStartInstanceMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGceFailedToStartInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop instance {0}. {1}.
        /// </summary>
        public static string CloudExplorerGceFailedToStopInstanceMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGceFailedToStopInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Updating Firewall.
        /// </summary>
        public static string CloudExplorerGceFailedToUpdateFirewallCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceFailedToUpdateFirewallCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update Firewall rules for instance..
        /// </summary>
        public static string CloudExplorerGceFailedToUpdateFirewallMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGceFailedToUpdateFirewallMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Engine Properties.
        /// </summary>
        public static string CloudExplorerGceInstanceAppEngineCategory {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceAppEngineCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Properties.
        /// </summary>
        public static string CloudExplorerGceInstanceCategory {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The internal IP address of the instance.
        /// </summary>
        public static string CloudExplorerGceInstanceInternalIpDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceInternalIpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal IP Address.
        /// </summary>
        public static string CloudExplorerGceInstanceInternalIpDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceInternalIpDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The machine type for the instance.
        /// </summary>
        public static string CloudExplorerGceInstanceMachineTypeDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceMachineTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Type.
        /// </summary>
        public static string CloudExplorerGceInstanceMachineTypeDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceMachineTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The App Engine module for the instance..
        /// </summary>
        public static string CloudExplorerGceInstanceModuleDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceModuleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the instance.
        /// </summary>
        public static string CloudExplorerGceInstanceNameDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public IP address of the instance.
        /// </summary>
        public static string CloudExplorerGceInstancePublicIpDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstancePublicIpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External IP Address.
        /// </summary>
        public static string CloudExplorerGceInstancePublicIpDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstancePublicIpDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting tags for {0}.
        /// </summary>
        public static string CloudExplorerGceInstanceSettingTagsCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceSettingTagsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting {0}.
        /// </summary>
        public static string CloudExplorerGceInstanceStartingCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceStartingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current status of the instance.
        /// </summary>
        public static string CloudExplorerGceInstanceStatusDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping {0}.
        /// </summary>
        public static string CloudExplorerGceInstanceStoppingCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceStoppingCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tags for the instance..
        /// </summary>
        public static string CloudExplorerGceInstanceTagsDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceTagsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating firewall for {0}.
        /// </summary>
        public static string CloudExplorerGceInstanceUpdatingFirewallCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceUpdatingFirewallCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the module for the instance..
        /// </summary>
        public static string CloudExplorerGceInstanceVersionDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Properties.
        /// </summary>
        public static string CloudExplorerGceInstanceWindowsCategory {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceWindowsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of Windows installed on the instance..
        /// </summary>
        public static string CloudExplorerGceInstanceWindowsVersionDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceWindowsVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Version.
        /// </summary>
        public static string CloudExplorerGceInstanceWindowsVersionDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceWindowsVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zone of the instance.
        /// </summary>
        public static string CloudExplorerGceInstanceZoneDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceInstanceZoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Firewall Ports....
        /// </summary>
        public static string CloudExplorerGceManageFirewallPortsMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerGceManageFirewallPortsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Windows Credentials....
        /// </summary>
        public static string CloudExplorerGceManageWindowsCredentialsMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerGceManageWindowsCredentialsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New ASP.NET Instance.
        /// </summary>
        public static string CloudExplorerGceNewAspNetInstanceMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerGceNewAspNetInstanceMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Instance.
        /// </summary>
        public static string CloudExplorerGceNewInstanceMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerGceNewInstanceMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No instances in this zone.
        /// </summary>
        public static string CloudExplorerGceNoInstancesInZoneCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceNoInstancesInZoneCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Windows instances in this zone.
        /// </summary>
        public static string CloudExplorerGceNoWindowsInstancesInZoneCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceNoWindowsInstancesInZoneCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only Windows instances.
        /// </summary>
        public static string CloudExplorerGceOnlyWindowsButtonToolTip {
            get {
                return ResourceManager.GetString("CloudExplorerGceOnlyWindowsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Terminal Server Session....
        /// </summary>
        public static string CloudExplorerGceOpenTerminalSessionMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerGceOpenTerminalSessionMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Web Site....
        /// </summary>
        public static string CloudExplorerGceOpenWebSiteMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerGceOpenWebSiteMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish settings saved to {0}.
        /// </summary>
        public static string CloudExplorerGcePublishingSettingsSavedMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGcePublishingSettingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Compute Engine.
        /// </summary>
        public static string CloudExplorerGceRootNodeCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceRootNodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Publish Settings.
        /// </summary>
        public static string CloudExplorerGceSavePublishSettingsDialogCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceSavePublishSettingsDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish settings file (*.publishsettings)|*.publishsettings.
        /// </summary>
        public static string CloudExplorerGceSavePublishSettingsExtensions {
            get {
                return ResourceManager.GetString("CloudExplorerGceSavePublishSettingsExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save publishing settings....
        /// </summary>
        public static string CloudExplorerGceSavePublishSettingsMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerGceSavePublishSettingsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose credentials for publish settings:.
        /// </summary>
        public static string CloudExplorerGceSavePubSettingsCredentialsMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGceSavePubSettingsCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose credentials.
        /// </summary>
        public static string CloudExplorerGceSavePubSettingsCredentialsTitle {
            get {
                return ResourceManager.GetString("CloudExplorerGceSavePubSettingsCredentialsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All OS Instances.
        /// </summary>
        public static string CloudExplorerGceShowAllOsInstancesCommand {
            get {
                return ResourceManager.GetString("CloudExplorerGceShowAllOsInstancesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Instances.
        /// </summary>
        public static string CloudExplorerGceShowInstancesCommand {
            get {
                return ResourceManager.GetString("CloudExplorerGceShowInstancesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Only Windows Instances.
        /// </summary>
        public static string CloudExplorerGceShowWindowsOnlyInstancesCommand {
            get {
                return ResourceManager.GetString("CloudExplorerGceShowWindowsOnlyInstancesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Zones.
        /// </summary>
        public static string CloudExplorerGceShowZonesCommand {
            get {
                return ResourceManager.GetString("CloudExplorerGceShowZonesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Google Compute Engine API is not enabled for this project..
        /// </summary>
        public static string CloudExplorerGceSourceApiDisabledMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGceSourceApiDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load instances data..
        /// </summary>
        public static string CloudExplorerGceSourceFailedLoadingZonesCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceSourceFailedLoadingZonesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading instances data....
        /// </summary>
        public static string CloudExplorerGceSourceLoadingZonesCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceSourceLoadingZonesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No zones found..
        /// </summary>
        public static string CloudExplorerGceSourceNoZonesCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceSourceNoZonesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start {0}?.
        /// </summary>
        public static string CloudExplorerGceStartInstanceConfirmationPrompt {
            get {
                return ResourceManager.GetString("CloudExplorerGceStartInstanceConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start {0}.
        /// </summary>
        public static string CloudExplorerGceStartInstanceConfirmationPromptCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceStartInstanceConfirmationPromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start instance.
        /// </summary>
        public static string CloudExplorerGceStartInstanceMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerGceStartInstanceMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start instance operation for {0} failed. {1}.
        /// </summary>
        public static string CloudExplorerGceStartOperationFailedMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGceStartOperationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to stop {0}?.
        /// </summary>
        public static string CloudExplorerGceStopInstanceConfirmationPrompt {
            get {
                return ResourceManager.GetString("CloudExplorerGceStopInstanceConfirmationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop {0}.
        /// </summary>
        public static string CloudExplorerGceStopInstanceConfirmationPromptCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGceStopInstanceConfirmationPromptCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop instance.
        /// </summary>
        public static string CloudExplorerGceStopInstanceMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerGceStopInstanceMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop instance operation for {0} failed. {1}.
        /// </summary>
        public static string CloudExplorerGceStopOperationFailedMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGceStopOperationFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone Properties.
        /// </summary>
        public static string CloudExplorerGceZoneCategory {
            get {
                return ResourceManager.GetString("CloudExplorerGceZoneCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the zone..
        /// </summary>
        public static string CloudExplorerGceZoneDescriptionDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceZoneDescriptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the zone..
        /// </summary>
        public static string CloudExplorerGceZoneNameDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceZoneNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The region for the zone..
        /// </summary>
        public static string CloudExplorerGceZoneRegionDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceZoneRegionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The status of the zone..
        /// </summary>
        public static string CloudExplorerGceZoneStatusDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGceZoneStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket Properties.
        /// </summary>
        public static string CloudExplorerGcsBucketCategory {
            get {
                return ResourceManager.GetString("CloudExplorerGcsBucketCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The creation time stamp for the bucket.
        /// </summary>
        public static string CloudExplorerGcsBucketCreatedDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGcsBucketCreatedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The location where the bucket resides..
        /// </summary>
        public static string CloudExplorerGcsBucketLocationDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGcsBucketLocationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string CloudExplorerGcsBucketLocationDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGcsBucketLocationDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The modification time stamp for the bucket.
        /// </summary>
        public static string CloudExplorerGcsBucketModifiedDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGcsBucketModifiedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the bucket.
        /// </summary>
        public static string CloudExplorerGcsBucketNameDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGcsBucketNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage class for the bucket.
        /// </summary>
        public static string CloudExplorerGcsBucketStorageClassDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGcsBucketStorageClassDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Class.
        /// </summary>
        public static string CloudExplorerGcsBucketStorageClassDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGcsBucketStorageClassDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether versioning is enabled for the bucket.
        /// </summary>
        public static string CloudExplorerGcsBucketVersioningEnabledDescription {
            get {
                return ResourceManager.GetString("CloudExplorerGcsBucketVersioningEnabledDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Versioning Enabled.
        /// </summary>
        public static string CloudExplorerGcsBucketVersioningEnabledDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerGcsBucketVersioningEnabledDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to list buckets..
        /// </summary>
        public static string CloudExplorerGcsFailedToListBucketsCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGcsFailedToListBucketsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading buckets....
        /// </summary>
        public static string CloudExplorerGcsLoadingBucketsCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGcsLoadingBucketsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No buckets found..
        /// </summary>
        public static string CloudExplorerGcsNoBucketsFoundCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGcsNoBucketsFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Cloud Storage.
        /// </summary>
        public static string CloudExplorerGcsRootNodeCaption {
            get {
                return ResourceManager.GetString("CloudExplorerGcsRootNodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Buckets.
        /// </summary>
        public static string CloudExplorerGcsShowBucketsCommand {
            get {
                return ResourceManager.GetString("CloudExplorerGcsShowBucketsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Locations.
        /// </summary>
        public static string CloudExplorerGcsShowLocationsCommand {
            get {
                return ResourceManager.GetString("CloudExplorerGcsShowLocationsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Google Cloud Storage API is not enabled for this project..
        /// </summary>
        public static string CloudExplorerGcsSourceApiDisabledMessage {
            get {
                return ResourceManager.GetString("CloudExplorerGcsSourceApiDisabledMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string CloudExplorerLoadingMessage {
            get {
                return ResourceManager.GetString("CloudExplorerLoadingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or Create Account.
        /// </summary>
        public static string CloudExplorerNoAccountButtonCaption {
            get {
                return ResourceManager.GetString("CloudExplorerNoAccountButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new account or select and existing one..
        /// </summary>
        public static string CloudExplorerNoAccountMessage {
            get {
                return ResourceManager.GetString("CloudExplorerNoAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to Cloud Console.
        /// </summary>
        public static string CloudExplorerNoProjectButtonCaption {
            get {
                return ResourceManager.GetString("CloudExplorerNoProjectButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects found.
        /// </summary>
        public static string CloudExplorerNoProjectsFoundPlaceholderMessage {
            get {
                return ResourceManager.GetString("CloudExplorerNoProjectsFoundPlaceholderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string CloudExplorerRefreshButtonToolTip {
            get {
                return ResourceManager.GetString("CloudExplorerRefreshButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select account....
        /// </summary>
        public static string CloudExplorerSelectAccountMessage {
            get {
                return ResourceManager.GetString("CloudExplorerSelectAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backend Type.
        /// </summary>
        public static string CloudExplorerSqlBackendTypeDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerSqlBackendTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Version.
        /// </summary>
        public static string CloudExplorerSqlDatabaseVersionDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerSqlDatabaseVersionDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the list of Google Cloud SQL instances..
        /// </summary>
        public static string CloudExplorerSqlFailedMessage {
            get {
                return ResourceManager.GetString("CloudExplorerSqlFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to list instances..
        /// </summary>
        public static string CloudExplorerSqlFailedToLoadInstancesCaption {
            get {
                return ResourceManager.GetString("CloudExplorerSqlFailedToLoadInstancesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Properties.
        /// </summary>
        public static string CloudExplorerSqlInstanceCategory {
            get {
                return ResourceManager.GetString("CloudExplorerSqlInstanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPv6 Address (First Gen).
        /// </summary>
        public static string CloudExplorerSqlInstanceIp6AddressDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerSqlInstanceIp6AddressDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string CloudExplorerSqlInstanceIpAddressDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerSqlInstanceIpAddressDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance Type.
        /// </summary>
        public static string CloudExplorerSqlInstanceTypeDisplayName {
            get {
                return ResourceManager.GetString("CloudExplorerSqlInstanceTypeDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading instances....
        /// </summary>
        public static string CloudExplorerSqlLoadingInstancesCaption {
            get {
                return ResourceManager.GetString("CloudExplorerSqlLoadingInstancesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Authorized Networks.
        /// </summary>
        public static string CloudExplorerSqlManageAuthorizedNetworksMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerSqlManageAuthorizedNetworksMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No instances found..
        /// </summary>
        public static string CloudExplorerSqlNoInstancesFoundCaption {
            get {
                return ResourceManager.GetString("CloudExplorerSqlNoInstancesFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Data Connection.
        /// </summary>
        public static string CloudExplorerSqlOpenAddDataConnectionMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerSqlOpenAddDataConnectionMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Cloud SQL.
        /// </summary>
        public static string CloudExplorerSqlRootNodeCaption {
            get {
                return ResourceManager.GetString("CloudExplorerSqlRootNodeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to updated authorized networks..
        /// </summary>
        public static string CloudExplorerSqlUpdateAthorizedNetworksErrorMessage {
            get {
                return ResourceManager.GetString("CloudExplorerSqlUpdateAthorizedNetworksErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating authorized networks....
        /// </summary>
        public static string CloudExplorerSqlUpdatedAthorizedNetworksCaption {
            get {
                return ResourceManager.GetString("CloudExplorerSqlUpdatedAthorizedNetworksCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string CloudExplorerStatusMenuHeader {
            get {
                return ResourceManager.GetString("CloudExplorerStatusMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Cloud Explorer ({0}).
        /// </summary>
        public static string CloudExplorerToolWindowCaption {
            get {
                return ResourceManager.GetString("CloudExplorerToolWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Cloud Explorer (select account).
        /// </summary>
        public static string CloudExplorerToolWindowCaptionNoAccount {
            get {
                return ResourceManager.GetString("CloudExplorerToolWindowCaptionNoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to publish project {0}..
        /// </summary>
        public static string GcePublishFailedMessage {
            get {
                return ResourceManager.GetString("GcePublishFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publishing {0} to Compute Engine..
        /// </summary>
        public static string GcePublishStepStartMessage {
            get {
                return ResourceManager.GetString("GcePublishStepStartMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project {0} succesfully published to Compute Engine instance {1}..
        /// </summary>
        public static string GcePublishSuccessMessage {
            get {
                return ResourceManager.GetString("GcePublishSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account {0} already exists..
        /// </summary>
        public static string ManageAccountsAccountAlreadyExistsPromptMessage {
            get {
                return ResourceManager.GetString("ManageAccountsAccountAlreadyExistsPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Account.
        /// </summary>
        public static string ManageAccountsAccountAlreadyExistsPromptTitle {
            get {
                return ResourceManager.GetString("ManageAccountsAccountAlreadyExistsPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        public static string ManageAccountsAddAccountButtonCaption {
            get {
                return ResourceManager.GetString("ManageAccountsAddAccountButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose account:.
        /// </summary>
        public static string ManageAccountsChooseAccountMessage {
            get {
                return ResourceManager.GetString("ManageAccountsChooseAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Account.
        /// </summary>
        public static string ManageAccountsCurrentAccountMessage {
            get {
                return ResourceManager.GetString("ManageAccountsCurrentAccountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ManageAccountsDeleteAccountButtonCaption {
            get {
                return ResourceManager.GetString("ManageAccountsDeleteAccountButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the account {0}?.
        /// </summary>
        public static string ManageAccountsDeleteAccountPromptMessage {
            get {
                return ResourceManager.GetString("ManageAccountsDeleteAccountPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Account.
        /// </summary>
        public static string ManageAccountsDeleteAccountPromptTitle {
            get {
                return ResourceManager.GetString("ManageAccountsDeleteAccountPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set As Current.
        /// </summary>
        public static string ManageAccountsSetAsCurrentAccountButtonCaption {
            get {
                return ResourceManager.GetString("ManageAccountsSetAsCurrentAccountButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Accounts.
        /// </summary>
        public static string ManageAccountsWindowTitle {
            get {
                return ResourceManager.GetString("ManageAccountsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Credentials.
        /// </summary>
        public static string ManageWindowsCredentialsAddCredentialsCaption {
            get {
                return ResourceManager.GetString("ManageWindowsCredentialsAddCredentialsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Credentials.
        /// </summary>
        public static string ManageWindowsCredentialsDeleteCredentialsCaption {
            get {
                return ResourceManager.GetString("ManageWindowsCredentialsDeleteCredentialsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to the delete the credentials for user {0}?.
        /// </summary>
        public static string ManageWindowsCredentialsDeleteCredentialsPromptMessage {
            get {
                return ResourceManager.GetString("ManageWindowsCredentialsDeleteCredentialsPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Credentials.
        /// </summary>
        public static string ManageWindowsCredentialsDeleteCredentialsPromptTitle {
            get {
                return ResourceManager.GetString("ManageWindowsCredentialsDeleteCredentialsPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Credentials.
        /// </summary>
        public static string ManageWindowsCredentialsShowCredentialsCaption {
            get {
                return ResourceManager.GetString("ManageWindowsCredentialsShowCredentialsCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows credentials for {0}.
        /// </summary>
        public static string ManageWindowsCredentialsWindowMessage {
            get {
                return ResourceManager.GetString("ManageWindowsCredentialsWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Windows Credentials.
        /// </summary>
        public static string ManageWindowsCredentialsWindowTitle {
            get {
                return ResourceManager.GetString("ManageWindowsCredentialsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download and install the MySQL Installer which will guide you through installing the needed extensions. After they are installed restart Visual Studio..
        /// </summary>
        public static string MySqlInstallerWindowBottomMessage {
            get {
                return ResourceManager.GetString("MySqlInstallerWindowBottomMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download MySQL for Visual Studio.
        /// </summary>
        public static string MySqlInstallerWindowTitle {
            get {
                return ResourceManager.GetString("MySqlInstallerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a Google Cloud SQL database as a Data Connection &quot;MySQL for Visual Studio&quot; must be installed. It is highly recommended that the &quot;MySQL Connector/Net&quot; also be installed to be able to properly interact with the database..
        /// </summary>
        public static string MySqlInstallerWindowTopMessage {
            get {
                return ResourceManager.GetString("MySqlInstallerWindowTopMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A browser window has been open to login into your account. To cancel this operation close the browser window and press Cancel to close this window. When the login finishes this window will close automatically..
        /// </summary>
        public static string OAuthFlowWindowMessage {
            get {
                return ResourceManager.GetString("OAuthFlowWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Account.
        /// </summary>
        public static string OAuthFlowWindowTitle {
            get {
                return ResourceManager.GetString("OAuthFlowWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Firewall Ports.
        /// </summary>
        public static string PortManagerWindowCaption {
            get {
                return ResourceManager.GetString("PortManagerWindowCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Firewall rules and tags to enable traffic for the instance.
        /// </summary>
        public static string PortManagerWindowMessage {
            get {
                return ResourceManager.GetString("PortManagerWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish {0}.
        /// </summary>
        public static string PublishDialogCaption {
            get {
                return ResourceManager.GetString("PublishDialogCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Engine Flex.
        /// </summary>
        public static string PublishDialogChoiceStepAppEngineFlexName {
            get {
                return ResourceManager.GetString("PublishDialogChoiceStepAppEngineFlexName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy to App Engine Flex.
        /// </summary>
        public static string PublishDialogChoiceStepAppEngineToolTip {
            get {
                return ResourceManager.GetString("PublishDialogChoiceStepAppEngineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compute Engine.
        /// </summary>
        public static string PublishDialogChoiceStepGceName {
            get {
                return ResourceManager.GetString("PublishDialogChoiceStepGceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy to Compute Engine.
        /// </summary>
        public static string PublishDialogChoiceStepGceToolTip {
            get {
                return ResourceManager.GetString("PublishDialogChoiceStepGceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a target:.
        /// </summary>
        public static string PublishDialogChoiceStepMessage {
            get {
                return ResourceManager.GetString("PublishDialogChoiceStepMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open website after publish process finishes.
        /// </summary>
        public static string PublishDialogGceStepOpenWebsiteCaption {
            get {
                return ResourceManager.GetString("PublishDialogGceStepOpenWebsiteCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select account:.
        /// </summary>
        public static string PublishDialogGceStepSelectCredentialsMessage {
            get {
                return ResourceManager.GetString("PublishDialogGceStepSelectCredentialsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select instance:.
        /// </summary>
        public static string PublishDialogGceStepSelectInstanceMessage {
            get {
                return ResourceManager.GetString("PublishDialogGceStepSelectInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish project to Google Cloud....
        /// </summary>
        public static string PublishDialogGenericMenuHeader {
            get {
                return ResourceManager.GetString("PublishDialogGenericMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string PublishDialogNextButtonCaption {
            get {
                return ResourceManager.GetString("PublishDialogNextButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prev.
        /// </summary>
        public static string PublishDialogPrevButtonCaption {
            get {
                return ResourceManager.GetString("PublishDialogPrevButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish {0} to Google Cloud....
        /// </summary>
        public static string PublishDialogProjectMenuHeader {
            get {
                return ResourceManager.GetString("PublishDialogProjectMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string PublishDialogPublishButtonCaption {
            get {
                return ResourceManager.GetString("PublishDialogPublishButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the password for the user {0} in instance {1}? This operation cannot be cancelled..
        /// </summary>
        public static string ResetPasswordConfirmationPromptMessage {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPasswordConfirmationPromptTitle {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationPromptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to reset password for {0}. {1}.
        /// </summary>
        public static string ResetPasswordFailedPromptMessage {
            get {
                return ResourceManager.GetString("ResetPasswordFailedPromptMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Google Cloud SDK.
        /// </summary>
        public static string ResetPasswordGcloudLinkCaption {
            get {
                return ResourceManager.GetString("ResetPasswordGcloudLinkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use this feature you need to have the &quot;beta&quot; component of the Google Cloud SDK installed. Please do so by running the command: gcloud components install beta..
        /// </summary>
        public static string ResetPasswordGcloudMissingBetaMessage {
            get {
                return ResourceManager.GetString("ResetPasswordGcloudMissingBetaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Google Cloud SDK Component.
        /// </summary>
        public static string ResetPasswordGcloudMissingComponentTitle {
            get {
                return ResourceManager.GetString("ResetPasswordGcloudMissingComponentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To use this feature you need to have the Google Cloud SDK is installed and available in the path, and that the &quot;beta&quot; component is installed. Please restart Visual Studio after the Google Cloud SDK has finished installing. You can install the Google Cloud SDK by following this link..
        /// </summary>
        public static string ResetPasswordGcloudMissingMessage {
            get {
                return ResourceManager.GetString("ResetPasswordGcloudMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Google Cloud SDK.
        /// </summary>
        public static string ResetPasswordMissingGcloudTitle {
            get {
                return ResourceManager.GetString("ResetPasswordMissingGcloudTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name:.
        /// </summary>
        public static string ResetPasswordUserNameCaption {
            get {
                return ResourceManager.GetString("ResetPasswordUserNameCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password for {0}.
        /// </summary>
        public static string ResetPasswordWindowTitle {
            get {
                return ResourceManager.GetString("ResetPasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The copy operation failed, this might happen if another program has the Windows Clipboard open, such as a virtual machine agent..
        /// </summary>
        public static string ShowPasswordCopyFailedMessage {
            get {
                return ResourceManager.GetString("ShowPasswordCopyFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Failed.
        /// </summary>
        public static string ShowPasswordCopyFailedTitle {
            get {
                return ResourceManager.GetString("ShowPasswordCopyFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Password.
        /// </summary>
        public static string ShowPasswordCopyPasswordButtonCaption {
            get {
                return ResourceManager.GetString("ShowPasswordCopyPasswordButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide password.
        /// </summary>
        public static string ShowPasswordHidePasswordTooltip {
            get {
                return ResourceManager.GetString("ShowPasswordHidePasswordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password for user {0} in instance {1} is:.
        /// </summary>
        public static string ShowPasswordMessage {
            get {
                return ResourceManager.GetString("ShowPasswordMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string ShowPasswordShowPasswordTooltip {
            get {
                return ResourceManager.GetString("ShowPasswordShowPasswordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for {0}.
        /// </summary>
        public static string ShowPasswordWindowTitle {
            get {
                return ResourceManager.GetString("ShowPasswordWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose credentials to use:.
        /// </summary>
        public static string TerminalServerManagerWindowMessage {
            get {
                return ResourceManager.GetString("TerminalServerManagerWindowMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Terminal Server session.
        /// </summary>
        public static string TerminalServerManagerWindowTitle {
            get {
                return ResourceManager.GetString("TerminalServerManagerWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string UiCancelButtonCaption {
            get {
                return ResourceManager.GetString("UiCancelButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string UiCloseButtonCaption {
            get {
                return ResourceManager.GetString("UiCloseButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string UiDeleteButtonCaption {
            get {
                return ResourceManager.GetString("UiDeleteButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string UiDownloadButtonCaption {
            get {
                return ResourceManager.GetString("UiDownloadButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string UiOkButtonCaption {
            get {
                return ResourceManager.GetString("UiOkButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open on Cloud Console.
        /// </summary>
        public static string UiOpenOnCloudConsoleMenuHeader {
            get {
                return ResourceManager.GetString("UiOpenOnCloudConsoleMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string UiPropertiesMenuHeader {
            get {
                return ResourceManager.GetString("UiPropertiesMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string UiSaveButtonCaption {
            get {
                return ResourceManager.GetString("UiSaveButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        public static string UiUndoButtonCaption {
            get {
                return ResourceManager.GetString("UiUndoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Windows Credentials.
        /// </summary>
        public static string WindowsCredentialsChooserButtonToolTip {
            get {
                return ResourceManager.GetString("WindowsCredentialsChooserButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No credentials found....
        /// </summary>
        public static string WindowsCredentialsChooserNoCredentialsFoundMessage {
            get {
                return ResourceManager.GetString("WindowsCredentialsChooserNoCredentialsFoundMessage", resourceCulture);
            }
        }
    }
}
