using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Optimization;
using System.Web.Routing;
using System.Configuration;

namespace $safeprojectname$
{
    public class MvcApplication : System.Web.HttpApplication
    {
        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
        }

        protected void Application_Error()
        {
            HandleUnconfiguredDatabaseConnectionString();
        }

        /// <summary>
        /// Default value of the database connection string generated by this ASP.NET application template.
        /// </summary>
        const string ConnectionStringPlaceholder = "Server=[IPv4 IP Address];Database=[Database name];Uid=[User name];Pwd=[User password]";

        /// <summary>
        /// On application error, check the value of the DefaultConnection database connection string.
        /// If the connection string has not been configured, redirect to a page that provides instructions
        /// for configuring this application to use a Cloud SQL database, as well as additional resources. 
        /// </summary>
        void HandleUnconfiguredDatabaseConnectionString()
        {
            var connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"]?.ConnectionString;

            if (connectionString == ConnectionStringPlaceholder)
            {
                Response.Redirect("/Content/GoogleCloudSQLConfiguration.html");
            }
        }
    }
}
